export const INSERT_ABOVE = 'INSERT_ABOVE';
export const INSERT_BELOW = 'INSERT_BELOW';
export const INSERT_TO_THE_LEFT_OF = 'INSERT_TO_THE_LEFT_OF';
export const INSERT_TO_THE_RIGHT_OF = 'INSERT_TO_THE_RIGHT_OF';

export const RESIZE = 'RESIZE';

export const SHOW_INSERT_MENU = 'SHOW_INSERT_MENU';
export const HIDE_INSERT_MENU = 'HIDE_INSERT_MENU';

export const ADD = 'ADD';

export const DELETE_TILE = 'DELETE_TILE';

export const SET_TOOLTIP_TYPE = 'SET_TOOLTIP_TYPE';
export const SET_TOOLTIP_TILE_ID = 'SET_TOOLTIP_TILE_ID';
export const SET_TOOLTIP_CONTENT = 'SET_TOOLTIP_CONTENT';
export const SET_TOOLTIP_IS_VISIBLE = 'SET_TOOLTIP_IS_VISIBLE';
export const SUBMIT_TOOLTIP = 'SUBMIT_TOOLTIP';

