export const INSERT_ABOVE = 'INSERT_ABOVE';
export const INSERT_BELOW = 'INSERT_BELOW';
export const INSERT_TO_THE_LEFT_OF = 'INSERT_TO_THE_LEFT_OF';
export const INSERT_TO_THE_RIGHT_OF = 'INSERT_TO_THE_RIGHT_OF';

export const RESIZE = 'RESIZE';

export const SHOW_INSERT_MENU = 'SHOW_INSERT_MENU';
export const HIDE_INSERT_MENU = 'HIDE_INSERT_MENU';

export const ADD = 'ADD';

export const DELETE_TILE = 'DELETE_TILE';

//TODO: delete
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
